version: '2'

services:
  python:
    build: python/
    container_name: python
    tty: true
    volumes:
      - ./src:/usr/src/app
  db:
    image: mysql:5
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
       MYSQL_DATABASE: main
       MYSQL_ROOT_PASSWORD: test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=test
    ports:
     - 8080:80
    volumes:
      - /sessions
